### ISSUE TITLE
Cannot download pretrained models

### ISSUE THREAD

**Issue by leandro-gracia-gil** [daigo0927/tf-raft#24]
When trying to follow the README instructions you get access denied errors due to permissions in GCS.

For example, this is what you get when you try to access https://storage.googleapis.com/tf-raft-pretrained/2020-09-26T08-51/checkpoints
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>
```

Using gsutil raises similar errors.
AccessDeniedException: 403 user does not have storage.objects.list access to the Google Cloud Storage bucket.

Could you please fix GCS access permissions?
Thanks!

**Comment by daigo0927** [comment]
Thanks for your notification. Now I have fixed the storage permission and you would be able to download pretrained weights via `gsutil cp` as described in README. 👍

**Comment by leandro-gracia-gil** [comment]
Can confirm it works now. Thanks!
